import { PaymentBadge } from "../../../lib/types";

// Define payment badges data
export const paymentBadges: PaymentBadge[] = [
	{ id: "mastercard", name: "Mastercard", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mastercard_color.svg` },
	{ id: "visa", name: "Visa", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visa_1_color.svg` },
	{ id: "visa-alt", name: "Visa (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visa_2_color.svg` },
	{ id: "visa-electron", name: "Visa Electron", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visaelectron_color.svg` },
	{ id: "amex-1", name: "American Express", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/americanexpress_1_color.svg` },
	{ id: "amex-2", name: "American Express (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/americanexpress_2_color.svg` },
	{ id: "amex-3", name: "American Express (Simple)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amex_color.svg` },
	{ id: "apple-pay", name: "Apple Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/applepay_color.svg` },
	{ id: "apple-pay-alt", name: "Apple Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/applepay2_color.svg` },
	{ id: "google-pay", name: "Google Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/googlepay_color.svg` },
	{ id: "shop-pay", name: "Shop Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay_color.svg` },
	{ id: "shop-pay-2", name: "Shop Pay (Alt 1)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay2_color.svg` },
	{ id: "shop-pay-3", name: "Shop Pay (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay3_color.svg` },
	{ id: "paypal-1", name: "PayPal", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_1_color.svg` },
	{ id: "paypal-2", name: "PayPal (Alt 1)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_2_color.svg` },
	{ id: "paypal-3", name: "PayPal (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_3_color.svg` },
	{ id: "amazon-pay-1", name: "Amazon Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amazonpay_1_color.svg` },
	{ id: "amazon-pay-2", name: "Amazon Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amazonpay_2_color.svg` },
	{ id: "klarna", name: "Klarna", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/klarna_color.svg` },
	{ id: "afterpay", name: "Afterpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/afterpay_color.svg` },
	{ id: "alipay", name: "Alipay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alipay_color.svg` },
	{ id: "stripe", name: "Stripe", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/stripe_color.svg` },
	{ id: "bitcoin-1", name: "Bitcoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_1_color.svg` },
	{ id: "bitcoin-2", name: "Bitcoin (Alt 1)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_2_color.svg` },
	{ id: "bitcoin-3", name: "Bitcoin (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_3_color.svg` },
	{ id: "ethereum", name: "Ethereum", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/etherium_color.svg` },
	{ id: "dogecoin", name: "Dogecoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dogecoin_color.svg` },
	{ id: "dogecoin-2", name: "Dogecoin (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dogecoin2_color.svg` },
	{ id: "litecoin", name: "Litecoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/litecoin_color.svg` },
	{ id: "monero", name: "Monero", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/monero_color.svg` },
	{ id: "ripple", name: "Ripple", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ripple_color.svg` },
	{ id: "usd-coin", name: "USD Coin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/usdcoin_color.svg` },
	{ id: "maestro", name: "Maestro", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/maestro_color.svg` },
	{ id: "discover", name: "Discover", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/discover_color.svg` },
	{ id: "jcb", name: "JCB", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jcb_color.svg` },
	{ id: "diners-club-1", name: "Diners Club", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dinersclub_1_color.svg` },
	{ id: "diners-club-2", name: "Diners Club (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dinersclub_2_color.svg` },
	{ id: "union-pay", name: "Union Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/unionpay_color.svg` },
	{ id: "wechat-pay", name: "WeChat Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/wechatpay_color.svg` },
	{ id: "ideal", name: "iDEAL", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ideal_color.svg` },
	{ id: "giropay", name: "Giropay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/giropay_color.svg` },
	{ id: "sofort", name: "Sofort", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sofort_color.svg` },
	{ id: "sepa", name: "SEPA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sepa_color.svg` },
	{ id: "bancontact", name: "Bancontact", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancontact_color.svg` },
	{ id: "bancontact-2", name: "Bancontact (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancontact2_color.svg` },
	{ id: "eps", name: "EPS", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/eps_color.svg` },
	{ id: "p24", name: "Przelewy24", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/przelewy24_color.svg` },
	{ id: "multibanco", name: "Multibanco", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/multibanco_color.svg` },
	{ id: "interac", name: "Interac", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/interac_1_color.svg` },
	{ id: "interac-2", name: "Interac (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/interac_2_color.svg` },
	{ id: "affirm", name: "Affirm", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/affirm_color.svg` },
	{ id: "clearpay", name: "Clearpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/clearpay_color.svg` },
	{ id: "zip-pay", name: "Zip Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zippay_color.svg` },
	{ id: "quadpay", name: "QuadPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/quadpay_color.svg` },
	{ id: "sezzle", name: "Sezzle", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sezzle_color.svg` },
	{ id: "splitit", name: "Splitit", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/splitit_color.svg` },
	{ id: "shopify-1", name: "Shopify", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shopify_1_color.svg` },
	{ id: "shopify-2", name: "Shopify (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shopify_2_color.svg` },
];
