interface PaymentBadge {
	id: string;
	name: string;
	image: string;
}

export const paymentBadges: PaymentBadge[] = [
	{ id: "mastercard", name: "Mastercard", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mastercard_color.svg` },
	{ id: "visa-1", name: "Visa", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visa_1_color.svg` },
	{ id: "paypal-1", name: "PayPal", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_1_color.svg` },
	{ id: "apple-pay", name: "Apple Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/applepay_color.svg` },
	{ id: "stripe", name: "Stripe", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/stripe_color.svg` },
	{ id: "amazon-pay-2", name: "Amazon Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amazonpay_2_color.svg` },
	{ id: "american-express-1", name: "American Express", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/americanexpress_1_color.svg` },
	{ id: "akulaku", name: "Akulaku", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/akulaku_color.svg` },
	{ id: "alandsbanken", name: "Alandsbanken", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alandsbanken_color.svg` },
	{ id: "alcohol-free", name: "Alcohol Free", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alcoholfree_color.svg` },
	{ id: "alfaclick", name: "Alfaclick", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alfaclick_color.svg` },
	{ id: "alfamart", name: "Alfamart", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alfamart_color.svg` },
	{ id: "alipay", name: "Alipay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alipay_color.svg` },
	{ id: "alipay-hk", name: "Alipay HK", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alipayhk_color.svg` },
	{ id: "alma", name: "Alma", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alma_color.svg` },
	{ id: "alpha-bank", name: "Alpha Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/alphabank_color.svg` },
	{ id: "amazon-pay-1", name: "Amazon Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amazonpay_1_color.svg` },
	{ id: "american-express-2", name: "American Express (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/americanexpress_2_color.svg` },
	{ id: "amex", name: "Amex", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/amex_color.svg` },
	{ id: "anyday", name: "Anyday", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/anyday_color.svg` },
	{ id: "apple-pay-2", name: "Apple Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/applepay2_color.svg` },
	{ id: "appmax", name: "Appmax", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/appmax_color.svg` },
	{ id: "aramex", name: "Aramex", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/aramex_color.svg` },
	{ id: "athmobil", name: "ATH Mobil", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/athmobil_color.svg` },
	{ id: "atm", name: "ATM", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/atm_color.svg` },
	{ id: "atome", name: "Atome", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/atome_color.svg` },
	{ id: "authorized-dealer-1", name: "Authorized Dealer", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/authorizeddealer1_color.svg` },
	{ id: "authorized-dealer-2", name: "Authorized Dealer (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/authorizeddealer2_color.svg` },
	{ id: "bance-intesa", name: "Bance Intesa", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/banceintesa_color.svg` },
	{ id: "banco-bradesco", name: "Banco Bradesco", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancobradesco_color.svg` },
	{ id: "banco-colombia", name: "Banco Colombia", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancocolombia_color.svg` },
	{ id: "banco-de-bogota", name: "Banco de Bogota", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancodebogota_color.svg` },
	{ id: "banco-do-brasil", name: "Banco do Brasil", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancodobrasil_color.svg` },
	{ id: "banco-estado", name: "Banco Estado", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancoestado_color.svg` },
	{ id: "banco-general", name: "Banco General", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancogeneral_color.svg` },
	{ id: "bancomat", name: "Bancomat", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancomat_color.svg` },
	{ id: "bancontact-2", name: "Bancontact (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancontact2_color.svg` },
	{ id: "bancontact", name: "Bancontact", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bancontact_color.svg` },
	{ id: "bank-deposit", name: "Bank Deposit", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bankdeposit_color.svg` },
	{ id: "bank-transfer", name: "Bank Transfer", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/banktransfer_color.svg` },
	{ id: "banorte", name: "Banorte", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/banorte_color.svg` },
	{ id: "baroda", name: "Baroda", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/baroda_color.svg` },
	{ id: "bbb", name: "BBB", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bbb_color.svg` },
	{ id: "bbva-bancomer", name: "BBVA Bancomer", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bbvabancomer_color.svg` },
	{ id: "bca", name: "BCA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bca_color.svg` },
	{ id: "bcp", name: "BCP", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bcp_color.svg` },
	{ id: "bdo", name: "BDO", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bdo_color.svg` },
	{ id: "belfius", name: "Belfius", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/belfius_color.svg` },
	{ id: "bhim", name: "BHIM", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bhim_color.svg` },
	{ id: "billease", name: "BillEase", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/billease_color.svg` },
	{ id: "billpay", name: "BillPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/billpay_color.svg` },
	{ id: "billplz", name: "Billplz", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/billplz_color.svg` },
	{ id: "billpocket", name: "Billpocket", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/billpocket_color.svg` },
	{ id: "bit", name: "Bit", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bit_color.svg` },
	{ id: "bitcoin-1", name: "Bitcoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_1_color.svg` },
	{ id: "bitcoin-2", name: "Bitcoin (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_2_color.svg` },
	{ id: "bitcoin-3", name: "Bitcoin (Simple)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoin_3_color.svg` },
	{ id: "bitcoin-cash", name: "Bitcoin Cash", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitcoincash_color.svg` },
	{ id: "bitpay", name: "BitPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bitpay_color.svg` },
	{ id: "bizum", name: "Bizum", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bizum_color.svg` },
	{ id: "blik", name: "BLIK", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/blik_color.svg` },
	{ id: "bluepay", name: "BluePay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bluepay_color.svg` },
	{ id: "bol", name: "BOL", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bol_color.svg` },
	{ id: "boleto-bancario", name: "Boleto Bancário", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/boleto_bancario_color.svg` },
	{ id: "boleto", name: "Boleto", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/boleto_color.svg` },
	{ id: "boost", name: "Boost", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/boost_color.svg` },
	{ id: "bpay", name: "BPAY", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bpay_color.svg` },
	{ id: "bpi", name: "BPI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bpi_color.svg` },
	{ id: "bpost", name: "bpost", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/bpost_color.svg` },
	{ id: "braintree", name: "Braintree", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/braintree_color.svg` },
	{ id: "brt", name: "BRT", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/brt_color.svg` },
	{ id: "cartasi", name: "CartaSi", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cartasi_color.svg` },
	{ id: "carte-bleue", name: "Carte Bleue", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cartebleue_color.svg` },
	{ id: "cash-app", name: "Cash App", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cashapp_color.svg` },
	{ id: "cash-in-advance", name: "Cash in Advance", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cashinadvance_color.svg` },
	{ id: "cash-on-delivery", name: "Cash on Delivery", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cashondelivery_color.svg` },
	{ id: "cash-on-pickup", name: "Cash on Pickup", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cashonpickup_color.svg` },
	{ id: "charity-2", name: "Charity (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/charity_2_color.svg` },
	{ id: "charity", name: "Charity", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/charity_color.svg` },
	{ id: "cimb-bank-malaysia", name: "CIMB Bank Malaysia", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cimbbankmalaysia_color.svg` },
	{ id: "cirrus", name: "Cirrus", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cirrus_color.svg` },
	{ id: "citadele", name: "Citadele", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/citadele_color.svg` },
	{ id: "citi", name: "Citi", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/citi_color.svg` },
	{ id: "clearpay", name: "Clearpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/clearpay_color.svg` },
	{ id: "click-and-buy", name: "Click&Buy", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/clickandbuy_color.svg` },
	{ id: "clickbank", name: "ClickBank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/clickbank_color.svg` },
	{ id: "cmi", name: "CMI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cmi_color.svg` },
	{ id: "coinbase", name: "Coinbase", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/coinbase_color.svg` },
	{ id: "coinpayments", name: "CoinPayments", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/coinpayments_color.svg` },
	{ id: "coins-ph", name: "Coins.ph", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/coinsph_color.svg` },
	{ id: "colissimo", name: "Colissimo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/colissimo_color.svg` },
	{ id: "correios", name: "Correios", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/correios_color.svg` },
	{ id: "cronos", name: "Cronos", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/cronos_color.svg` },
	{ id: "cruelty-free", name: "Cruelty Free", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/crueltyfree_color.svg` },
	{ id: "dai", name: "DAI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dai_color.svg` },
	{ id: "daily", name: "Daily", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/daily_color.svg` },
	{ id: "dankort", name: "Dankort", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dankort_color.svg` },
	{ id: "danske-bank", name: "Danske Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/danskebank_color.svg` },
	{ id: "dash", name: "Dash", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dash_color.svg` },
	{ id: "davivienda", name: "Davivienda", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/davivienda_color.svg` },
	{ id: "desjardins", name: "Desjardins", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/desjardins_color.svg` },
	{ id: "deutsche-post-2", name: "Deutsche Post (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/deutschepost_2_color.svg` },
	{ id: "dina-card", name: "Dina Card", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dinacard_color.svg` },
	{ id: "diners-club-1", name: "Diners Club", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dinersclub_1_color.svg` },
	{ id: "diners-club-2", name: "Diners Club (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dinersclub_2_color.svg` },
	{ id: "direct-debit", name: "Direct Debit", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/directdebit_color.svg` },
	{ id: "discover", name: "Discover", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/discover_color.svg` },
	{ id: "dogecoin-2", name: "Dogecoin (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dogecoin2_color.svg` },
	{ id: "dogecoin", name: "Dogecoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dogecoin_color.svg` },
	{ id: "dpd", name: "DPD", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/dpd_color.svg` },
	{ id: "easypaisa", name: "Easypaisa", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/easypaisa_color.svg` },
	{ id: "ec", name: "EC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ec_color.svg` },
	{ id: "eco-friendly", name: "Eco Friendly", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ecofriendly_color.svg` },
	{ id: "efecty", name: "Efecty", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/efecty_color.svg` },
	{ id: "elo-1", name: "Elo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/elo_1_color.svg` },
	{ id: "elo-2", name: "Elo (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/elo_2_color.svg` },
	{ id: "emi", name: "EMI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/emi_color.svg` },
	{ id: "empat-kali", name: "Empat Kali", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/empatkali_color.svg` },
	{ id: "eps", name: "EPS", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/eps_color.svg` },
	{ id: "etherium", name: "Etherium", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/etherium_color.svg` },
	{ id: "ethically-sourced", name: "Ethically Sourced", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ethicallysourced_color.svg` },
	{ id: "eurobank", name: "Eurobank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/eurobank_color.svg` },
	{ id: "expert-advice", name: "Expert Advice", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/expertadvice_color.svg` },
	{ id: "express-shipping", name: "Express Shipping", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/expressshipping_color.svg` },
	{ id: "facebook-pay", name: "Facebook Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/facebookpay_color.svg` },
	{ id: "family-mart", name: "Family Mart", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/familymart_color.svg` },
	{ id: "fast-shipping", name: "Fast Shipping", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/fastshipping_color.svg` },
	{ id: "fda-registered", name: "FDA Registered", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/fdaregistered_color.svg` },
	{ id: "first-bank-plc", name: "First Bank PLC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/firstbankplc_color.svg` },
	{ id: "flattr", name: "Flattr", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/flattr_color.svg` },
	{ id: "float", name: "Float", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/float_color.svg` },
	{ id: "four2", name: "Four2", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/four2_color.svg` },
	{ id: "fps-2", name: "FPS (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/fps_2_color.svg` },
	{ id: "fps", name: "FPS", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/fps_color.svg` },
	{ id: "freecharge", name: "Freecharge", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/freecharge_color.svg` },
	{ id: "free-delivery", name: "Free Delivery", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/freedelivery_color.svg` },
	{ id: "free-returns", name: "Free Returns", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/freereturns_color.svg` },
	{ id: "free-shipping-1", name: "Free Shipping", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/freeshipping_1_color.svg` },
	{ id: "free-shipping-2", name: "Free Shipping (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/freeshipping_2_color.svg` },
	{ id: "garanti-pay", name: "Garanti Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/garantipay_color.svg` },
	{ id: "gcash-1", name: "GCash", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gcash1_color.svg` },
	{ id: "gcash-2", name: "GCash (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gcash2_color.svg` },
	{ id: "genoa-pay", name: "Genoa Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/genoapay_color.svg` },
	{ id: "giropay", name: "Giropay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/giropay_color.svg` },
	{ id: "global-blue", name: "Global Blue", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/globalblue_color.svg` },
	{ id: "gls", name: "GLS", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gls_color.svg` },
	{ id: "gogo-express", name: "GoGo Express", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gogoexpress_color.svg` },
	{ id: "google-pay", name: "Google Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/googlepay_color.svg` },
	{ id: "google-wallet-1", name: "Google Wallet", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/googlewallet_1_color.svg` },
	{ id: "google-wallet-2", name: "Google Wallet (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/googlewallet_2_color.svg` },
	{ id: "gopay-2", name: "GoPay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gopay2_color.svg` },
	{ id: "gopay", name: "GoPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gopay_color.svg` },
	{ id: "grab", name: "Grab", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/grab_color.svg` },
	{ id: "grabpay", name: "GrabPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/grabpay_color.svg` },
	{ id: "gratipay", name: "Gratipay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/gratipay_color.svg` },
	{ id: "guarantee-included", name: "Guarantee Included", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/guaranteeincluded_color.svg` },
	{ id: "guaranty-trust-bank", name: "Guaranty Trust Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/guarantytrustbank_color.svg` },
	{ id: "handelsbanken", name: "Handelsbanken", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/handelsbanken_color.svg` },
	{ id: "hdfc", name: "HDFC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/hdfc_color.svg` },
	{ id: "hipercard", name: "Hipercard", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/hipercard_color.svg` },
	{ id: "hsbc", name: "HSBC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/hsbc_color.svg` },
	{ id: "icici", name: "ICICI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/icici_color.svg` },
	{ id: "ideal", name: "iDEAL", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ideal_color.svg` },
	{ id: "in3", name: "in3", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/in3_color.svg` },
	{ id: "indusind", name: "IndusInd", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/indusind_color.svg` },
	{ id: "ing", name: "ING", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ing_color.svg` },
	{ id: "inpost", name: "InPost", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/inpost_color.svg` },
	{ id: "instacred", name: "InstaCred", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/instacred_color.svg` },
	{ id: "instant-download", name: "Instant Download", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/instantdownload_color.svg` },
	{ id: "interac-1", name: "Interac", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/interac_1_color.svg` },
	{ id: "interac-2", name: "Interac (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/interac_2_color.svg` },
	{ id: "interbank", name: "Interbank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/interbank_color.svg` },
	{ id: "invoice", name: "Invoice", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/invoice_color.svg` },
	{ id: "ipay88", name: "iPay88", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ipay88_color.svg` },
	{ id: "itau-unibanco", name: "Itaú Unibanco", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/itauunibanco_color.svg` },
	{ id: "iyzico", name: "iyzico", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/iyzico_color.svg` },
	{ id: "jad", name: "JAD", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jad_color.svg` },
	{ id: "japan-post", name: "Japan Post", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/japanpost_color.svg` },
	{ id: "jcb", name: "JCB", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jcb_color.svg` },
	{ id: "jko-pay", name: "JKO Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jkopay_color.svg` },
	{ id: "jousto", name: "Jousto", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jousto_color.svg` },
	{ id: "jt-express", name: "J&T Express", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/jtexpress_color.svg` },
	{ id: "juice", name: "Juice", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/juice_color.svg` },
	{ id: "kbc-cbc", name: "KBC/CBC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/kbccbc_color.svg` },
	{ id: "klarna", name: "Klarna", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/klarna_color.svg` },
	{ id: "knet", name: "KNET", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/knet_color.svg` },
	{ id: "kotak", name: "Kotak", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/kotak_color.svg` },
	{ id: "krevido", name: "Krevido", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/krevido_color.svg` },
	{ id: "kueski-pay", name: "Kueski Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/kueskipay_color.svg` },
	{ id: "la-poste", name: "La Poste", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/laposte_color.svg` },
	{ id: "latitude-pay", name: "Latitude Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/latitudepay_color.svg` },
	{ id: "lawson", name: "Lawson", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/lawson_color.svg` },
	{ id: "laybuy", name: "Laybuy", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/laybuy_color.svg` },
	{ id: "lbc", name: "LBC", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/lbc_color.svg` },
	{ id: "le-panier-bleu", name: "Le Panier Bleu", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/lepanierbleu_color.svg` },
	{ id: "line-pay", name: "LINE Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/linepay_color.svg` },
	{ id: "litecoin", name: "Litecoin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/litecoin_color.svg` },
	{ id: "luminor", name: "Luminor", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/luminor_color.svg` },
	{ id: "mach", name: "MACH", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mach_color.svg` },
	{ id: "mada", name: "mada", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mada_color.svg` },
	{ id: "made-in-the-us", name: "Made in the US", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/madeintheus_color.svg` },
	{ id: "maestro", name: "Maestro", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/maestro_color.svg` },
	{ id: "malayan-banking-berhad", name: "Malayan Banking Berhad", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/malayanbankingberhad_color.svg` },
	{ id: "mandiri", name: "Mandiri", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mandiri_color.svg` },
	{ id: "maroof", name: "Maroof", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/maroof_color.svg` },
	{ id: "maybank-qr-pay", name: "Maybank QRPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/maybankqrpay_color.svg` },
	{ id: "mb-way", name: "MB WAY", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mbway_color.svg` },
	{ id: "mercado-pago-1", name: "Mercado Pago", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mercadopago_1_color.svg` },
	{ id: "mercado-pago-2", name: "Mercado Pago (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mercadopago_2_color.svg` },
	{ id: "meta-pay", name: "Meta Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/metapay_color.svg` },
	{ id: "metrobank-blue", name: "Metrobank Blue", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/metrobankblue_color.svg` },
	{ id: "ministop", name: "Ministop", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ministop_color.svg` },
	{ id: "mobicred", name: "Mobicred", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mobicred_color.svg` },
	{ id: "mobile-pay", name: "MobilePay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mobilepay_color.svg` },
	{ id: "mobiqwik", name: "MobiKwik", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mobiqwik_color.svg` },
	{ id: "mollie", name: "Mollie", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mollie_color.svg` },
	{ id: "mol-pay", name: "MOLPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/molpay_color.svg` },
	{ id: "mondial-relay", name: "Mondial Relay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mondialrelay_color.svg` },
	{ id: "monero", name: "Monero", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/monero_color.svg` },
	{ id: "money-back-2", name: "Money Back (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/moneyback_2_color.svg` },
	{ id: "money-back", name: "Money Back", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/moneyback_color.svg` },
	{ id: "moneygram", name: "MoneyGram", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/moneygram_color.svg` },
	{ id: "moov", name: "Moov", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/moov_color.svg` },
	{ id: "mpesa", name: "M-PESA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mpesa_color.svg` },
	{ id: "mr-speedy", name: "Mr Speedy", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mrspeedy_color.svg` },
	{ id: "mtn", name: "MTN", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mtn_color.svg` },
	{ id: "multibanco", name: "Multibanco", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/multibanco_color.svg` },
	{ id: "multicaja", name: "Multicaja", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/multicaja_color.svg` },
	{ id: "mytm-money", name: "MyTM Money", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/mytmoney_color.svg` },
	{ id: "nanti-aja", name: "Nanti Aja", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nantiaja_color.svg` },
	{ id: "nbc-canada", name: "NBC Canada", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nbccanada_color.svg` },
	{ id: "negara", name: "Negara", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/negara_color.svg` },
	{ id: "nequi", name: "Nequi", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nequi_color.svg` },
	{ id: "netopia", name: "NETOPIA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/netopia_color.svg` },
	{ id: "newpay", name: "NewPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/newpay_color.svg` },
	{ id: "ninja-van", name: "Ninja Van", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ninjavan_color.svg` },
	{ id: "nordea", name: "Nordea", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nordea_color.svg` },
	{ id: "no-synthetic-colors", name: "No Synthetic Colors", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nosyntheticcolors_color.svg` },
	{ id: "no-toxic-chemicals", name: "No Toxic Chemicals", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/notoxicchemicals_color.svg` },
	{ id: "not-tested-on-animals", name: "Not Tested on Animals", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/nottestedonanimals_color.svg` },
	{ id: "oca-card", name: "OCA Card", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ocacard_color.svg` },
	{ id: "octopus", name: "Octopus", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/octopus_color.svg` },
	{ id: "ogone", name: "Ogone", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ogone_color.svg` },
	{ id: "ola-money", name: "Ola Money", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/olamoney_color.svg` },
	{ id: "oma-saastopankki", name: "Oma Säästöpankki", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/oma_saastopankki_color.svg` },
	{ id: "one-pay", name: "OnePay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/onepay_color.svg` },
	{ id: "oney", name: "Oney", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/oney_color.svg` },
	{ id: "open-pay", name: "OpenPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/openpay_color.svg` },
	{ id: "orange-mobile", name: "Orange Mobile", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/orangemobile_color.svg` },
	{ id: "osuuspankki", name: "Osuuspankki", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/osuuspankki_color.svg` },
	{ id: "oxxo", name: "OXXO", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/oxxo_color.svg` },
	{ id: "ozow", name: "Ozow", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ozow_color.svg` },
	{ id: "pace", name: "Pace", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pace_color.svg` },
	{ id: "pago-facil", name: "Pago Fácil", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pagofacil_color.svg` },
	{ id: "pagseguro-1", name: "PagSeguro", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pagseguro_1_color.svg` },
	{ id: "pagseguro-2", name: "PagSeguro (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pagseguro_2_color.svg` },
	{ id: "paidy", name: "Paidy", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paidy_color.svg` },
	{ id: "pallex", name: "Pallex", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pallex_color.svg` },
	{ id: "paraben-free", name: "Paraben Free", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/parabenfree_color.svg` },
	{ id: "pay-bright", name: "PayBright", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paybright_color.svg` },
	{ id: "payfast", name: "PayFast", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payfast_color.svg` },
	{ id: "payflex", name: "PayFlex", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payflex_color.svg` },
	{ id: "paygate", name: "PayGate", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paygate_color.svg` },
	{ id: "pay-just-now", name: "PayJustNow", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payjustnow_color.svg` },
	{ id: "paylife", name: "PayLife", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paylife_color.svg` },
	{ id: "paymaya", name: "PayMaya", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paymaya_color.svg` },
	{ id: "payme", name: "PayMe", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payme_color.svg` },
	{ id: "payment-on-delivery", name: "Payment on Delivery", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paymentondelivery_color.svg` },
	{ id: "paymongo", name: "PayMongo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paymongo_color.svg` },
	{ id: "paynow-2", name: "PayNow (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paynow2_color.svg` },
	{ id: "paypal-2", name: "PayPal (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_2_color.svg` },
	{ id: "paypal-3", name: "PayPal (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypal_3_color.svg` },
	{ id: "paypay", name: "PayPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paypay_color.svg` },
	{ id: "100-percent-genuine", name: "100% Genuine", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/100percentgenuine_color.svg` },
	{ id: "100-percent-quality-guarantee", name: "100% Quality Guarantee", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/100percentqualityguarantee_color.svg` },
	{ id: "100-percent-risk-free", name: "100% Risk Free", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/100percentriskfree_color.svg` },
	{ id: "100-percent-satisfaction", name: "100% Satisfaction", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/100percentsatisfaction_color.svg` },
	{ id: "14-days-money-back", name: "14 Days Money Back", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/14daysmoneyback_color.svg` },
	{ id: "1-to-2-weeks", name: "1-2 Weeks", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/1to2weeks_color.svg` },
	{ id: "1-to-3-weeks", name: "1-3 Weeks", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/1to3weeks_color.svg` },
	{ id: "24-7-support", name: "24/7 Support", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/247support_color.svg` },
	{ id: "256-bit-ssl-secure-2", name: "256-bit SSL Secure (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/256bitsslsecure_2_color.svg` },
	{ id: "256-bit-ssl-secure", name: "256-bit SSL Secure", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/256bitsslsecure_color.svg` },
	{ id: "2checkout", name: "2Checkout", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/2checkout_color.svg` },
	{ id: "2-day-delivery", name: "2 Day Delivery", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/2daydelivery_color.svg` },
	{ id: "2-to-3-weeks", name: "2-3 Weeks", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/2to3weeks_color.svg` },
	{ id: "3-to-5-weeks", name: "3-5 Weeks", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/3to5weeks_color.svg` },
	{ id: "5-to-7-days", name: "5-7 Days", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/5to7days_color.svg` },
	{ id: "60-days-money-back", name: "60 Days Money Back", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/60daysmoneyback_color.svg` },
	{ id: "7-eleven", name: "7-Eleven", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/7eleven_color.svg` },
	{ id: "abitab", name: "Abitab", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/abitab_color.svg` },
	{ id: "access-bank", name: "Access Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/accessbank_color.svg` },
	{ id: "affirm", name: "Affirm", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/affirm_color.svg` },
	{ id: "afterpay", name: "Afterpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/afterpay_color.svg` },
	{ id: "airtel", name: "Airtel", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/airtel_color.svg` },
	{ id: "airwallex", name: "Airwallex", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/airwallex_color.svg` },
	{ id: "aktia", name: "Aktia", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/aktia_color.svg` },
	{ id: "paysafe", name: "Paysafe", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paysafe_color.svg` },
	{ id: "paysera", name: "Paysera", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paysera_color.svg` },
	{ id: "payshop", name: "Payshop", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payshop_color.svg` },
	{ id: "paystack", name: "Paystack", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paystack_color.svg` },
	{ id: "paytm", name: "Paytm", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paytm_color.svg` },
	{ id: "paytrail", name: "Paytrail", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/paytrail_color.svg` },
	{ id: "payu", name: "PayU", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payu_color.svg` },
	{ id: "payzapp", name: "PayZapp", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/payzapp_color.svg` },
	{ id: "permata-bank", name: "Permata Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/permatabank_color.svg` },
	{ id: "pfx", name: "PFX", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pfx_color.svg` },
	{ id: "phonepe", name: "PhonePe", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/phonepe_color.svg` },
	{ id: "piraeus-bank", name: "Piraeus Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/piraeusbank_color.svg` },
	{ id: "pivo", name: "Pivo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pivo_color.svg` },
	{ id: "pix", name: "PIX", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/pix_color.svg` },
	{ id: "polipay", name: "PoliPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/polipay_color.svg` },
	{ id: "poppankki", name: "POP Pankki", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/poppankki_color.svg` },
	{ id: "postepay-1", name: "Postepay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postepay_1_color.svg` },
	{ id: "postepay-2", name: "Postepay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postepay_2_color.svg` },
	{ id: "postfinance", name: "PostFinance", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postfinance_color.svg` },
	{ id: "posti", name: "Posti", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/posti_color.svg` },
	{ id: "postnl", name: "PostNL", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postnl_color.svg` },
	{ id: "postnord", name: "PostNord", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postnord_color.svg` },
	{ id: "postpay", name: "Postpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/postpay_color.svg` },
	{ id: "powerpay", name: "PowerPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/powerpay_color.svg` },
	{ id: "przelewy24", name: "Przelewy24", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/przelewy24_color.svg` },
	{ id: "qisstpay", name: "QisstPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/qisstpay_color.svg` },
	{ id: "qiwi", name: "QIWI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/qiwi_color.svg` },
	{ id: "quadpay", name: "QuadPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/quadpay_color.svg` },
	{ id: "quickpay", name: "QuickPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/quickpay_color.svg` },
	{ id: "rakuten-pay", name: "Rakuten Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/rakutenpay_color.svg` },
	{ id: "rakyat", name: "Rakyat", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/rakyat_color.svg` },
	{ id: "ratenkauf", name: "Ratenkauf", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ratenkauf_color.svg` },
	{ id: "razorpay", name: "Razorpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/razorpay_color.svg` },
	{ id: "rbl", name: "RBL", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/rbl_color.svg` },
	{ id: "recharge", name: "Recharge", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/recharge_color.svg` },
	{ id: "rechnung", name: "Rechnung", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/rechnung_color.svg` },
	{ id: "reclame-aqui", name: "Reclame Aqui", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/reclameaqui_color.svg` },
	{ id: "redcompr", name: "Redcompr", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/redcompr_color.svg` },
	{ id: "redpagos", name: "Redpagos", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/redpagos_color.svg` },
	{ id: "returns-accepted", name: "Returns Accepted", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/returnsaccepted_color.svg` },
	{ id: "revolut-1", name: "Revolut", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/revolut1_color.svg` },
	{ id: "revolut-2", name: "Revolut (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/revolut2_color.svg` },
	{ id: "revolut-3", name: "Revolut (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/revolut3_color.svg` },
	{ id: "ripple", name: "Ripple", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/ripple_color.svg` },
	{ id: "route-shipping-insurance", name: "Route Shipping Insurance", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/routeshippinginsurance_color.svg` },
	{ id: "rupay", name: "RuPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/rupay_color.svg` },
	{ id: "s-pankki", name: "S-Pankki", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/s-pankki_color.svg` },
	{ id: "saastopankki", name: "Säästöpankki", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/saastopankki_color.svg` },
	{ id: "sadad", name: "SADAD", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sadad_color.svg` },
	{ id: "safaricom", name: "Safaricom", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/safaricom_color.svg` },
	{ id: "sage", name: "Sage", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sage_color.svg` },
	{ id: "samsung-pay-1", name: "Samsung Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/samsungpay1_color.svg` },
	{ id: "samsung-pay-2", name: "Samsung Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/samsungpay2_color.svg` },
	{ id: "satisfait-ou-rembourse", name: "Satisfait ou Remboursé", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/satisfaitourembourse_color.svg` },
	{ id: "satispay", name: "Satispay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/satispay_color.svg` },
	{ id: "sberbank", name: "Sberbank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sberbank_color.svg` },
	{ id: "scalapay", name: "Scalapay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/scalapay_color.svg` },
	{ id: "seb", name: "SEB", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/seb_color.svg` },
	{ id: "secure-checkout", name: "Secure Checkout", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/securecheckout_color.svg` },
	{ id: "seicomart", name: "Seicomart", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/seicomart_color.svg` },
	{ id: "sencillito", name: "Sencillito", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sencillito_color.svg` },
	{ id: "sepa", name: "SEPA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sepa_color.svg` },
	{ id: "servipag", name: "Servipag", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/servipag_color.svg` },
	{ id: "sezzle", name: "Sezzle", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sezzle_color.svg` },
	{ id: "ships-from-usa", name: "Ships from USA", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shipsfromusa_color.svg` },
	{ id: "shopee-pay", name: "ShopeePay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shopeepay_color.svg` },
	{ id: "shop-humm", name: "Shop Humm", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shophumm_color.svg` },
	{ id: "shopify-1", name: "Shopify", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shopify_1_color.svg` },
	{ id: "shopify-2", name: "Shopify (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shopify_2_color.svg` },
	{ id: "shop-pay-2", name: "Shop Pay (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay2_color.svg` },
	{ id: "shop-pay-3", name: "Shop Pay (Alt 2)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay3_color.svg` },
	{ id: "shop-pay", name: "Shop Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/shoppay_color.svg` },
	{ id: "siauliu", name: "Šiaulių", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/siauliu_color.svg` },
	{ id: "siirto", name: "Siirto", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/siirto_color.svg` },
	{ id: "simpl", name: "Simpl", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/simpl_color.svg` },
	{ id: "sinpe-movil", name: "SINPE Móvil", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sinpemovil_color.svg` },
	{ id: "six", name: "SIX", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/six_color.svg` },
	{ id: "skrill", name: "Skrill", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/skrill_color.svg` },
	{ id: "snap-scan", name: "SnapScan", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/snapscan_color.svg` },
	{ id: "sodexo", name: "Sodexo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sodexo_color.svg` },
	{ id: "sofort-2", name: "Sofort (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sofort_2_color.svg` },
	{ id: "sofort", name: "Sofort", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sofort_color.svg` },
	{ id: "spei", name: "SPEI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/spei_color.svg` },
	{ id: "splitit", name: "Splitit", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/splitit_color.svg` },
	{ id: "square-1", name: "Square", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/square_1_color.svg` },
	{ id: "square-2", name: "Square (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/square_2_color.svg` },
	{ id: "ssl-secure", name: "SSL Secure", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sslsecure_color.svg` },
	{ id: "ssl-secure-color", name: "SSL Secure Color", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/sslsecurecolor_color.svg` },
	{ id: "standard-chartered", name: "Standard Chartered", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/standardchartered_color.svg` },
	{ id: "stc-pay", name: "STC Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/stcpay_color.svg` },
	{ id: "superior-quality", name: "Superior Quality", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/superiorquality_color.svg` },
	{ id: "swedback", name: "Swedback", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/swedback_color.svg` },
	{ id: "swish", name: "Swish", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/swish_color.svg` },
	{ id: "tabby", name: "Tabby", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/tabby_color.svg` },
	{ id: "telr", name: "Telr", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/telr_color.svg` },
	{ id: "tigo", name: "Tigo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/tigo_color.svg` },
	{ id: "touch-n-go", name: "Touch 'n Go", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/touchngo_color.svg` },
	{ id: "touch-n-go-ewallet", name: "Touch 'n Go eWallet", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/touchngoewallet_color.svg` },
	{ id: "transbank", name: "Transbank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/transbank_color.svg` },
	{ id: "transferwise", name: "TransferWise", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/transferwise_color.svg` },
	{ id: "troy", name: "Troy", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/troy_color.svg` },
	{ id: "trustly", name: "Trustly", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/trustly_color.svg` },
	{ id: "twint", name: "TWINT", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/twint_color.svg` },
	{ id: "twispay", name: "Twispay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/twispay_color.svg` },
	{ id: "union-bank-of-the-philippines", name: "Union Bank of the Philippines", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/unionbankofthephilippines_color.svg` },
	{ id: "union-pay", name: "UnionPay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/unionpay_color.svg` },
	{ id: "upi", name: "UPI", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/upi_color.svg` },
	{ id: "usda-registered", name: "USDA Registered", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/usdaregistered_color.svg` },
	{ id: "usd-coin", name: "USD Coin", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/usdcoin_color.svg` },
	{ id: "usps", name: "USPS", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/usps_color.svg` },
	{ id: "vegan-product", name: "Vegan Product", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/veganproduct_color.svg` },
	{ id: "venmo-1", name: "Venmo", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/venmo_1_color.svg` },
	{ id: "venmo-2", name: "Venmo (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/venmo_2_color.svg` },
	{ id: "verve", name: "Verve", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/verve_color.svg` },
	{ id: "viabill", name: "ViaBill", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/viabill_color.svg` },
	{ id: "vipps", name: "Vipps", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/vipps_color.svg` },
	{ id: "visa-2", name: "Visa (Alt)", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visa_2_color.svg` },
	{ id: "visa-electron", name: "Visa Electron", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/visaelectron_color.svg` },
	{ id: "viva-wallet", name: "Viva Wallet", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/vivawallet_color.svg` },
	{ id: "vodacom", name: "Vodacom", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/vodacom_color.svg` },
	{ id: "vorkasse-2", name: "Vorkasse", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/vorkasse_2_color.svg` },
	{ id: "walley", name: "Walley", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/walley_color.svg` },
	{ id: "webmoney", name: "WebMoney", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/webmoney_color.svg` },
	{ id: "webpay-oneclick", name: "Webpay OneClick", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/webpayoneclick_color.svg` },
	{ id: "webpay-plus", name: "Webpay Plus", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/webpayplus_color.svg` },
	{ id: "wechat-pay", name: "WeChat Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/wechatpay_color.svg` },
	{ id: "wepay", name: "WePay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/wepay_color.svg` },
	{ id: "western-union", name: "Western Union", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/westernunion_color.svg` },
	{ id: "wirecard", name: "Wirecard", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/wirecard_color.svg` },
	{ id: "wire-transfer", name: "Wire Transfer", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/wiretransfer_color.svg` },
	{ id: "worldpay", name: "Worldpay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/worldpay_color.svg` },
	{ id: "yandex-money", name: "Yandex Money", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/yandexmoney_color.svg` },
	{ id: "yes", name: "YES", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/yes_color.svg` },
	{ id: "yoco", name: "Yoco", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/yoco_color.svg` },
	{ id: "zapper", name: "Zapper", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zapper_color.svg` },
	{ id: "zelle", name: "Zelle", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zelle_color.svg` },
	{ id: "zenith-bank", name: "Zenith Bank", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zenithbank_color.svg` },
	{ id: "zest", name: "Zest", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zest_color.svg` },
	{ id: "zettle", name: "Zettle", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zettle_color.svg` },
	{ id: "zip-pay", name: "Zip Pay", image: `${window.txBadgesSettings.pluginUrl}assets/images/badges/zippay_color.svg` },
];
